{% set version = "0.6.0" %}

package:
    name: betamax
    version: {{ version }}

source:
    fn: betamax-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/b/betamax/betamax-{{ version }}.tar.gz
    md5: f70c210d760f5962c03d83eca4ec18ea

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - requests >=2.0

test:
    imports:
        - betamax
        - betamax.cassette
        - betamax.matchers
        - betamax.serializers

about:
    home: https://github.com/sigmavirus24/betamax
    license: Apache
    summary: A VCR imitation for python-requests

extra:
    recipe-maintainers:
        - ocefpaf
