{% set version = "0.7.1" %}

package:
    name: betamax
    version: {{ version }}

source:
    fn: betamax-{{ version }}.tar.gz
    url: https://github.com/sigmavirus24/betamax/archive/{{ version }}.tar.gz
    sha256: a128d61905a2e50bd6f2a38b9154ed0e4111f50a156bc25faec61b077f748fdf

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - requests >=2.0

test:
    imports:
        - betamax
        - betamax.cassette
        - betamax.matchers
        - betamax.serializers

about:
    home: https://github.com/sigmavirus24/betamax
    license: Apache-2.0
    summary: A VCR imitation for python-requests

extra:
    recipe-maintainers:
        - ocefpaf
        - sigmavirus24
